### ISSUE TITLE
Uranus's moons

### ISSUE THREAD

**Issue by dgasmith** [MolSSI-SSS/planets#1]
The information about Uranus's moon is incomplete!

**Comment by jchodera** [comment]
Which specific source line are you referring to?

**Comment by dgasmith** [comment]
Please check [this](https://github.com/MolSSI-SSS/planets/blob/master/Uranus#L1) out.

```python
for x in range(5):
   print(x)
```

**Comment by jchodera** [comment]
Huh:
```
Uranus 27 moons: Titania Oberon Umbriel Ariel Miranda
```
You're right, that's a bug. Pull requests to fix are welcomed!

**Comment by jchodera** [comment]
I bet you could use the [Wikipedia page for Uranus](https://en.wikipedia.org/wiki/Moons_of_Uranus#Names) as a source.
